name: weather_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  flutter_screenutil: ^5.9.3
  easy_localization: ^3.0.7
  flutter_bloc: ^8.1.6
  path_provider: ^2.1.5
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.3.3
  equatable: ^2.0.7
  flutter_animate: ^4.5.2
  weather: ^3.1.1
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/icons/

  fonts:
     - family: Overpass
       fonts:
         - asset: assets/fonts/Overpass/Overpass-Black.ttf
         - asset: assets/fonts/Overpass/Overpass-Bold.ttf
         - asset: assets/fonts/Overpass/Overpass-ExtraBold.ttf
         - asset: assets/fonts/Overpass/Overpass-ExtraLight.ttf
         - asset: assets/fonts/Overpass/Overpass-Light.ttf
         - asset: assets/fonts/Overpass/Overpass-Medium.ttf
         - asset: assets/fonts/Overpass/Overpass-Regular.ttf
         - asset: assets/fonts/Overpass/Overpass-SemiBold.ttf
         - asset: assets/fonts/Overpass/Overpass-Thin.ttf
